travis:
  secure:
    BINSTAR_TOKEN: BDIGe8wH4FPnVlSSuuxTWqC0bDknITv85Y1Sy0m4lbLAvNyCDQJuPQL8FNHWjZc1AK+uljV0pyFcUXyKj0FBYlMR7NHLD5CHe5Yugrr1Djj4UQjM3/HNB49pK7jspFMjFSMY4HoslCz0+lzCAwj/7i4ZINZtRkhPEaDAI3KxBMElbeOVledf42IHcWaDhMw/fj04okgEyIdlRTvi3gsTLhUj3tFQL1m3LcOyQtjCNqgYE9LSwzt+utXUp2OOhlRFR3s79m4VdI/7ZMAo116pnfHXQxmt0yqtHgVSfl1NrCASeovP3JylPq7NUG+OAE89rIHTb6OStbsB10lneae4DorBc9T+r1LG0xXXzTFfUfc8bQlkbakzb1GGIP+smvayARTJOrjLLH9QgtjyeMtcF/Yl2/zOjSE8QwzpGZxXwwXZm7E0Ynna6nAYyh2d1s9quaW9Whsbs9KGkx3hN5rftIaGS5DtgEvQ9SY9nQWEVtoTjDMf+GGvyx3+iwdUEnVuSwUw/5AMRNqKvS0d+tEGi8giYO+RxUXyiZ4RJfvqMhiQ6MMtE+SmnMUvOKsuqU+bPYTGFv7a4FtQUxwjUkFSAoqbQvyI1UpBKsWoaPflnkG97HyZ/hr+xfDbDRUImh+Im7+TgeLIa5B3icXqJARvtW5dSfBlpBIcna7UUQOWIpo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
